In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/Spotify Million Song Dataset_exported.csv")

df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57650 entries, 0 to 57649
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  57650 non-null  object
 1   song    57650 non-null  object
 2   link    57650 non-null  object
 3   text    57650 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB

In [5]:
df.columns

Index(['artist', 'song', 'link', 'text'], dtype='object')

In [7]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [9]:
df.sample(5)

,artist,song,link,text
27481,Children,Build A Home,/c/children/build+a+home_20590451.html,"Deep the cellar, timbers high, \n(Both hands ..."
28082,Cliff Richard,High Class Baby,/c/cliff+richard/high+class+baby_20212392.html,"Well you can't be my lovin' baby, you ain't go..."
29936,Dolly Parton,Daddy Won't Be Home Anymore,/d/dolly+parton/daddy+wont+be+home+anymore_201...,As I look around the little house we were so h...
38667,Jose Mari Chan,Radio Romance,/j/jose+mari+chan/radio+romance_21063808.html,The music of love that sings forever is on you...
8284,Incognito,Always There,/i/incognito/always+there_20067107.html,Such a good feeling \nThat's where I want to ...

In [13]:
df = df[['artist', 'song', 'text']]
df.head()

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante","Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...

In [15]:
df.dropna(subset=['text'], inplace=True)
df.isnull().sum()

artist    0
song      0
text      0
dtype: int64

In [17]:
import re

def clean_text(text):
    text = text.lower()                                      # lowercase
    text = re.sub(r'\[.*?\]', '', text)                       # remove [chorus] etc
    text = re.sub(r'https?://\S+|www\.\S+', '', text)         # remove links
    text = re.sub(r'[^a-zA-Z\s]', '', text)                   # keep letters only
    text = re.sub(r'\s+', ' ', text).strip()                  # remove extra spaces
    return text

df['clean_text'] = df['text'].apply(clean_text)
df.head()

,artist,song,text,clean_text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \nAnd...",look at her face its a wonderful face and it m...
1,ABBA,"Andante, Andante","Take it easy with me, please \nTouch me gentl...",take it easy with me please touch me gently li...
2,ABBA,As Good As New,I'll never know why I had to go \nWhy I had t...,ill never know why i had to go why i had to pu...
3,ABBA,Bang,Making somebody happy is a question of give an...,making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...,making somebody happy is a question of give an...

In [19]:
import nltk
from nltk.corpus import stopwords

stop = set(stopwords.words('english'))

df['clean_text'] = df['clean_text'].apply(lambda x: " ".join([word for word in x.split() if word not in stop]))
df.head()

,artist,song,text,clean_text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \nAnd...",look face wonderful face means something speci...
1,ABBA,"Andante, Andante","Take it easy with me, please \nTouch me gentl...",take easy please touch gently like summer even...
2,ABBA,As Good As New,I'll never know why I had to go \nWhy I had t...,ill never know go put lousy rotten show boy to...
3,ABBA,Bang,Making somebody happy is a question of give an...,making somebody happy question give take learn...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...,making somebody happy question give take learn...

In [21]:
df[['song','artist','clean_text']].sample(5)

,song,artist,clean_text
49607,Highway To Hell,Quiet Riot,living easy living free season ticket oneway r...
36714,Wish You Were Here,Incubus,dig toes sand ocean looks like thousand diamon...
28456,Love Twist,Culture Club,footsteps movements finding people clutch forb...
19570,Mary,Tori Amos,everybody wants something everybody want piece...
5130,Mansion On The Hill,Emmylou Harris,theres place edge town sir risin factories fie...